project:
  type: book
  output-dir: docs

book:
  title: "Redes Neurais Artificiais: um bom lugar para um estatístico se deitar"
  author: "Gustavo Almeida Silva e Tiago Maia Magalhães"
  date: "xx/xx/xxxx"
  cover-image: capa_livro.jpg
  chapters:
    - index.qmd
    - GD.qmd
    - neuron.qmd
    - summary.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

