---
title: "Introdução"
---

Modelos de regressão, cujos conceitos iniciais foram propostos por @Galton:1889, são modelos estatísticos que tentam explicar o comportamento de uma variável de interesse (ou resposta) a partir de covariáveis (variáveis explicativas) e parâmetros desconhecidos a serem estimados a partir de dados observáveis. Segundo @MontgomeryPeckVining:2021, esta é a técnica estatística mais utilizada. De maneira geral, uma função, denominada função de ligação, une uma característica da variável resposta, usualmente a média, a um certo preditor, constituído de parâmetros a serem estimados e variáveis explicativas.

Os primeiros modelos de regressão foram construídos assumindo-se que a variável resposta em estudo segue uma distribuição normal e que o preditor é uma função linear. Caso a suposição de normalidade não seja satisfeita, uma estratégia é buscar alguma transformação na variável resposta, como a proposta por @BoxCox:1964, na tentativa de garantir normalidade. Entretanto, as transformações podem dificultar a interpretação do modelo final.

A classe dos modelos linerares generalizados (MLG), apresentada por @NelderWedderburn:1972, flexibiliza a suposição distribucional dos dados, pois estendem a teoria da regressão normal para o caso em que a distribuição da variável resposta pertence a uma família exponencial.

Ainda assim, a suposição de linearidade do preditor com parâmetros a serem estimados nem sempre é apropriada. Nesses casos, alguns autores, como @Jorgensen:1983 e @CordeiroPaula:1989, propõem quantificar o efeito dessa relação através de uma relação não linear, conhecida. Na prática, é comum observarmos relações entre variável resposta e variável explicativa que são não lineares e desconhecidas. Daí surgiram os modelos não paramétricos em que não há a necessidade de prefixar uma relação a priori para ser utilizada no modelo. Existem diversas técnicas de regressão não paramétrica. Entre elas, há a regressão não paramétrica através de *splines*, em que funções são construídas por meio da junção de várias funções polinomiais de uma certa ordem que foram particionadas da variável explicativa a ser controlada de forma não paramétrica.
